#!/bin/bash

sudo apt update \
&& sudo apt upgrade -y \
&& sudo apt install -y \
	git \
	mysql-server-8.0 \
	certbot \
	nginx \
	redis-server \
	php7.4-fpm \
	php7.4-bcmath \
	php7.4-bz2 \
	php7.4-cli \
	php7.4-common \
	php7.4-curl \
	php7.4-gd \
	php7.4-json \
	php7.4-mbstring \
	php7.4-mysql \
	php7.4-xml \
	php7.4-zip \
	php7.4-sqlite3 \
	php-redis \
	sqlite3 \
	unzip \

curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
sudo apt-get install -y nodejs

php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"

php -r "if (hash_file('sha384', 'composer-setup.php') === '756890a4488ce9024fc62c56153228907f1545c228516cbf63f885e036d37e9a59d27d63f46af1d4d07ee0f76181c7d3') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"

php composer-setup.php

php -r "unlink('composer-setup.php');"

sudo mv composer.phar /usr/local/bin/composer
